---
title: "TT_WaterAccess"
author: "Jeff Grayum"
date: "6/4/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries       
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
library(lubridate)
library(countrycode)
#install.packages("ggmap")
library(ggmap)
```

Loading dataset
```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 19)

#cleaning the date format, and renaming
water <- tuesdata$water %>%
  mutate(report_date = mdy(report_date)) %>%
  rename(lat = lat_deg,
         lon = lon_deg,
         country = country_name) %>%
  separate(water_tech, c("water_tech", "brand"), sep = " - ",
           fill = "right") %>%
  mutate(install_year = ifelse(install_year > 2021, NA_real_, install_year)) %>%
  filter(!country %in% c("Peru", "Dominican Republic"),
         !is.na(country)) %>%
  filter(between(lat, -35, 37),
         between(lon, -40, 60))

water %>%
  view()

water %>%
  filter(!is.na(water_source)) %>%
  count(water_source, sort = TRUE) %>%
  head(10) %>%
  mutate(water_source = fct_reorder(water_source, n)) %>%
  ggplot(aes(n, water_source)) +
  geom_col() +
  labs(title = "Most common water sources",
       x = "",
       y = "Water source") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

water %>%
  count(status_id, sort = TRUE)

water %>%
  count(water_source, sort = TRUE)

water %>%
  count(water_tech, sort = TRUE)

water %>%
  count(brand, sort = TRUE)

water %>%
  filter(!is.na(water_tech),
         !is.na(brand)) %>%
  count(water_tech, brand, sort = TRUE)

water %>%
  filter(install_year > 1980) %>%
  count(install_year) %>%
  ggplot(aes(install_year, n)) +
  geom_col() +
  theme_fivethirtyeight() +
  labs(x = "Year of installation",
       y = "",
       title = "Water source technology installation year") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

water %>%
  count(country, sort = TRUE) %>%
  view()

water %>%
  count(installer, sort = TRUE)

water %>%
  count(status, sort = TRUE)

water %>%
  count(status_id, sort = TRUE)

water %>%
  count(status_id, status, sort = TRUE)
```

Next, we will make a map!!  But first, breakfast and moving cabins...
```{r}
countries = unique(water$country)

#try running just the firt two lines!
africa_map_data <- map_data("world") %>%
  as_tibble() %>%
  mutate(continent = countrycode(region, "country.name", "continent")) %>%
  filter(continent == "Africa") 

#First way to make map, using borders
water %>%
  filter(!is.na(country), 
         country != "Timor-Leste") %>%
  slice_sample(n = 10000) %>%
  ggplot(aes(lon, lat)) + 
  borders("world", regions = countries) +
  geom_point()

#Second, more controled way to make map (using geom_polygon)
water %>%
  filter(!is.na(country), 
         country != "Timor-Leste") %>%
  slice_sample(n = 10000) %>%
  ggplot(aes(lon, lat)) + 
  geom_polygon(aes(long, lat, group = group), 
               color = "black",
               fill = "white",
               size = 0.25,
               data = africa_map_data) +
  geom_point(size = 0.1, alpha = 0.25) +
  theme_map() +
  theme(legend.position = "none")



water %>%
  filter(country != "Timor-Leste") %>%
  group_by(country) %>%
  summarize(lat = mean(lat),
            lon = mean(lon)) %>%
  ggplot(aes(lon, lat)) +
  geom_point() +
  geom_text(aes(label = country, vjust = 1, hjust = 1))

```

Let's start looking at individual countries
```{r}
water %>%
  count(country, sort = TRUE)

#We'll start with Uganda, since we have the most data there.

#Removing theme_map allows us to see lat/lon and adjust filter!
water_uganda <- water %>%
  filter(country == "Uganda",
         between(lat, -2, 4),
         between(lon, 29.4, 35))

water_uganda %>%
  ggplot(aes(lon, lat)) + 
  borders("world", regions = "Uganda") +
  geom_point(size = 0.1, alpha = 0.25) +
  theme_map() +
  theme(legend.position = "none")

water_uganda %>%
  ggplot(aes(lon, lat, color = status_id)) + 
  borders("world", regions = "Uganda") +
  geom_point(size = 0.1, alpha = 0.25) +
  theme_map() +
  scale_color_discrete(guide = guide_legend(override.aes = list(size = 2, alpha = 1))) +
  theme(legend.position = "right") +
  labs(color = "Status",
       title = "Uganda's water sources")

 #Let's add terrain (lakes, mountains, etc) with ggmap!
#OK we're not going to do this because it requires an API key!
#When we google a map of Uganda, it shows the bottom right of the country is Lake Victoria --> hence the missing data there.

bbox <- c(left = 29.2, bottom = -2, right = 35, top = 4)


uganda_map <- get_stamenmap(bbox, zoom = 8)

water_uganda %>%
  count(water_source, sort = TRUE)

water_uganda_lumped2 <- water_uganda %>%
  mutate(water_source = fct_lump(water_source, 5)) %>%
  replace_na(list(water_source = "Other")) %>%
  view()

ggmap(uganda_map) +
  geom_point(aes(lon, lat), 
             data = water_uganda_lumped2, size = 0.1, alpha = 0.1) +
  facet_wrap(~ water_source)
```

